name: jar_video_player
description: "A new Flutter package project."
version: 0.1.0
homepage:


environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  visibility_detector: ^0.4.0+2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0





flutter:































